### ISSUE TITLE
Error on completing story

### ISSUE THREAD

**Issue by cafestifflered** [GamerSafer/ablockalypse#18]
```[13:33:21 INFO]: [Ablockalypse] The player 9e8fc99f-2f06-4629-be1c-5251dcab1892 just completed a story as a CONSTRUCTION_WORKER
[13:33:21 WARN]: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/lkeehl/tagapi/TagAPI
[13:33:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[13:33:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:761)
[13:33:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
[13:33:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
[13:33:21 WARN]:        at ablockalypse-all-1.0-SNAPSHOT.jar//com.gamersafer.minecraft.ablockalypse.listener.PlayerDeathListener.onPlayerDeath(PlayerDeathListener.java:45)
[13:33:21 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[13:33:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:33:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:33:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
[13:33:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:904)
[13:33:21 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:867)
[13:33:21 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1452)
[13:33:21 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:938)
[13:33:21 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1032)
[13:33:21 WARN]:        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1278)
[13:33:21 WARN]:        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2040)
[13:33:21 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2541)
[13:33:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[13:33:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[13:33:21 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2468)
[13:33:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[13:33:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[13:33:21 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[13:33:21 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:33:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:33:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:33:21 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[13:33:21 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[13:33:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[13:33:21 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[13:33:21 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[13:33:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:33:21 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1448)
[13:33:21 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[13:33:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:33:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:33:21 WARN]: Caused by: java.lang.NoClassDefFoundError: com/lkeehl/tagapi/TagAPI
[13:33:21 WARN]:        at ablockalypse-all-1.0-SNAPSHOT.jar//com.gamersafer.minecraft.ablockalypse.CharacterNametagManager.lambda$updateTag$3(CharacterNametagManager.java:28)
[13:33:21 WARN]:        at ablockalypse-all-1.0-SNAPSHOT.jar//com.gamersafer.minecraft.ablockalypse.AblockalypsePlugin.sync(AblockalypsePlugin.java:161)
[13:33:21 WARN]:        at ablockalypse-all-1.0-SNAPSHOT.jar//com.gamersafer.minecraft.ablockalypse.CharacterNametagManager.updateTag(CharacterNametagManager.java:27)
[13:33:21 WARN]:        at ablockalypse-all-1.0-SNAPSHOT.jar//com.gamersafer.minecraft.ablockalypse.listener.PlayerDeathListener.lambda$onPlayerDeath$3(PlayerDeathListener.java:69)
[13:33:21 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
[13:33:21 WARN]:        ... 34 more
[13:33:21 WARN]: Caused by: java.lang.ClassNotFoundException: com.lkeehl.tagapi.TagAPI
[13:33:21 WARN]:        ... 39 more```

**Comment by cafestifflered** [comment]
Fixed by using the no-tags branch and installing TagAPI plugin. Leaving this open for now as we need to be aware of it whenever the Thief is brought back.
