### ISSUE TITLE
Error on server restart

### ISSUE THREAD

**Issue by cafestifflered** [GamerSafer/ablockalypse#4]
```
[17:03:59 INFO]: [Ablockalypse] Enabling Ablockalypse v${version}
[17:03:59 INFO]: [Ablockalypse] TagAPI is using entity metadata from 1.17.1 for this version of Minecraft.
[17:03:59 ERROR]: Error occurred while enabling Ablockalypse v${version} (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because "protocolManager" is null
        at com.lkeehl.tagapi.TagListener.<init>(TagListener.java:200) ~[ablockalypse-all-1.0-SNAPSHOT.jar:?]
        at com.lkeehl.tagapi.TagAPI.onEnable(TagAPI.java:50) ~[ablockalypse-all-1.0-SNAPSHOT.jar:?]
        at com.gamersafer.minecraft.ablockalypse.AblockalypsePlugin.onEnable(AblockalypsePlugin.java:57) ~[ablockalypse-all-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:03:59 INFO]: [Ablockalypse] Disabling Ablockalypse v${version}
[17:03:59 ERROR]: Error occurred while disabling Ablockalypse v${version} (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.gamersafer.minecraft.ablockalypse.database.api.StoryStorage.shutdown()" because "this.storyStorage" is null
        at com.gamersafer.minecraft.ablockalypse.AblockalypsePlugin.onDisable(AblockalypsePlugin.java:101) ~[ablockalypse-all-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by SpaicyGaming** [comment]
A fixed version has been uploaded to the server
